// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAErVmXnu-MQjfiy5bOnZsmKvxd5AeZiwQ',
    appId: '1:1057462701122:web:7ffc95ddf81fd3ec3271db',
    messagingSenderId: '1057462701122',
    projectId: 'chat-354c3',
    authDomain: 'chat-354c3.firebaseapp.com',
    storageBucket: 'chat-354c3.appspot.com',
    measurementId: 'G-7NRSPTVSVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNol4muvUjekuyvWGeRX7wTa9TXvLrC2M',
    appId: '1:1057462701122:android:1d6c42b3e36d81b43271db',
    messagingSenderId: '1057462701122',
    projectId: 'chat-354c3',
    storageBucket: 'chat-354c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcIbZhIJg8J_W6quGDLY-aj7Ui7wpSbDk',
    appId: '1:1057462701122:ios:93c26148337cc60a3271db',
    messagingSenderId: '1057462701122',
    projectId: 'chat-354c3',
    storageBucket: 'chat-354c3.appspot.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcIbZhIJg8J_W6quGDLY-aj7Ui7wpSbDk',
    appId: '1:1057462701122:ios:93c26148337cc60a3271db',
    messagingSenderId: '1057462701122',
    projectId: 'chat-354c3',
    storageBucket: 'chat-354c3.appspot.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAErVmXnu-MQjfiy5bOnZsmKvxd5AeZiwQ',
    appId: '1:1057462701122:web:c5f2a1165e5f25f53271db',
    messagingSenderId: '1057462701122',
    projectId: 'chat-354c3',
    authDomain: 'chat-354c3.firebaseapp.com',
    storageBucket: 'chat-354c3.appspot.com',
    measurementId: 'G-PM2ZYLBP92',
  );
}
